### PR TITLE
fix bug in cpu op “Pad” ref, which could drop accuracy

### PR DESCRIPTION
**Pull request by ZhiquanWoW**

### CODE REVIEW

**Comment by ZhiquanWoW** [comment]
1

**Review by chenhu66 — CHANGES_REQUESTED** [review]
The original code is a bit weird, because i don't see how in_w<12 makes a difference. Your code is much readable. However, i don't think it's a bug. I think the result is the same, isn't it? If you agree, please change you commit message from "fix bug" to "improve code".

**Comment by ZhiquanWoW** [comment]
> The original code is a bit weird, because i don't see how in_w<12 makes a difference. Your code is much readable. However, i don't think it's a bug. I think the result is the same, isn't it? If you agree, please change you commit message from "fix bug" to "improve code".

lQLPDhtp2K95aefNAavNB0SwfG_q3MYYVn0CfheMS8ACAA_1860_427
我遇到这里有个bug，会影响模型最后的精度。具体模型的case我想不起来了(好像是input 16 padding到18)，如果你需要的话，我要去找找。现象是途中红色圈出的一列全部被错误padding为0了。加入这个修改后，数值正常了。

**Comment by ZhiquanWoW** [comment]
修复后图中的数据正常了，这里确实是有bug，不建议当作"improve code"

**Review by chenhu66 — APPROVED** [review]
不好意思，outw那边我没看仔细，原来的代码确实有问题。你这个例子很好，帮我理解了。

**Review by BUG1989 — APPROVED** [review]
lgtm

**Pull request merged**
