### PR TITLE
fix build convert_tool on windows

### PR DESCRIPTION
**Pull request by caishanli**
tested on windows an ubuntu20.04

### CODE REVIEW

**Comment by kalcohol** [comment]
dear, could u split this pr to several simpler ones?

**Comment by caishanli** [comment]
> dear, could u split this pr to several simpler ones?

next time will be!!!

**Comment by caishanli** [comment]
> dear, could u split this pr to several simpler ones?

by the way, when merge pr with ci check error means ci is no need any more.

**Comment by kalcohol** [comment]
why move ./example/common to ./common ?
because this not real tengine common codes. these examples may be refactored at future day, and the common could be very changeable.

**Comment by caishanli** [comment]
> why move ./example/common to ./common ?
> because this not real tengine common codes. these examples may be refactored at future day, and the common could be very changeable.

common/msc_getopt.h used by tools/demos/examples

**Comment by caishanli** [comment]
so need to modify?

**Pull request closed without merging**
