### PR TITLE
Add MegEngine Converter

### PR DESCRIPTION
**Pull request by yzchen**
MegEngine to Tengine Converter, by Megvii MegEngine Team.

### CODE REVIEW

**Comment by BUG1989** [comment]
Thanks for your contribution !

**Comment by BUG1989** [comment]
@kalcohol Please fix the failed of CI build.

**Comment by kalcohol** [comment]
> @kalcohol Please fix the failed of CI build.

╭(╯^╰)╮

**Comment by kalcohol** [comment]
@yzchen hi, i got error as below:
libmegengine-serializer.a(megengine_serializer.cpp.o)：in function 'TEngine::MegengineSerializer::LoadGraph(mgb::cg::ComputingGraphImpl*, TEngine::StaticGraph*)': 
megengine_serializer.cpp:(.text+0x7ba)：‘mgb::cg::ComputingGraphImpl::all_oprs() const’ undefined reference

is there anything that i was missed?

**Comment by yzchen** [comment]
> @yzchen hi, i got error as below:
> libmegengine-serializer.a(megengine_serializer.cpp.o)：in function 'TEngine::MegengineSerializer::LoadGraph(mgb::cg::ComputingGraphImpl*, TEngine::StaticGraph*)':
> megengine_serializer.cpp:(.text+0x7ba)：‘mgb::cg::ComputingGraphImpl::all_oprs() const’ undefined reference
> 
> is there anything that i was missed?

I think you should compile MegEngine with `Debug` mode or `RelWithDebInfo` mode. In default `Release` mode, this method(`all_oprs`) will be inlined.

for example:

```
cmake .. -DCMAKE_BUILD_TYPE=Debug -DMGE_WITH_TEST=ON
```

**Comment by yzchen** [comment]
# Compile

### MegEngine

```bash
git clone https://github.com/MegEngine/MegEngine.git
cd MegEngine
./third_party/prepare.sh
./third_party/install-mkl.sh
mkdir build && cd build
cmake .. -DMGE_WITH_TEST=OFF -DMGE_BUILD_SDK=OFF -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX={PREDEFINED_INSTALL_PATH}
make -j12
make install
make develop
export PYTHONPATH=/path/to/MegEngine/python_module

# test with python
 python3 -c "import megengine"

```

### TEngine

```bash
cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/x86_convert_tool.gcc.toolchain.cmake -DMEGENGINE_INSTALL_PATH={PREDEFINED_INSTALL_PATH} ..
```

# How to Get a model

~~Install a python library:~~

~~pip3 install megengine -f https://megengine.org.cn/whl/mge.html~~

Use previous `$PYTHONPATH`.

Dump a resnet18 model:
```python
import numpy as np
import megengine.hub
from megengine import jit
resnet18 = megengine.hub.load("megengine/models", "resnet18", pretrained=True)

@jit.trace(symbolic=True)
def infer_func(x):
    resnet18.eval()
    return resnet18(x)

x = np.random.random((1,3,224,224)).astype(np.float32)
infer_func.trace(x)
infer_func.dump('resnet18.megengine')
```

# Convert and Validate

Convert:

```bash
./tools/tools/convert_tools/convert_model_to_tm -f megengine -m ./models/resnet18.megengine -o ./models/resnet18.tmfile
```

Validate: get name of inputs and outputs

```python
import megengine._internal as mgb
*_, outputs = mgb.load_comp_graph_from_file('resnet18.megengine')
inputs = mgb.cgtools.get_dep_vars(outputs, 'Host2DeviceCopy')

print(inputs[0].name, inputs[0].imm_shape)
print(outputs[0].name, outputs[0].imm_shape)
```

run the model
```
import numpy as np
import megengine._internal as mgb
cg, _, outputs = mgb.load_comp_graph_from_file('resnet18.megengine')
inputs = mgb.cgtools.get_dep_vars(outputs, 'Host2DeviceCopy')
outputs = list(map(mgb.copy_output, outputs))
(outputs,) = outputs
f = cg.compile(inputs, outputs)
x = np.random.random((1,3,224,224)).astype(np.float32)
y = f(x)
```

**Pull request closed without merging**
